version: '2'
services:
    clinic-app:
        image: clinic
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://clinic-mysql:3306/clinic?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=clinic-elasticsearch:9300
        ports:
            - 8080:8080
    clinic-mysql:
        extends:
            file: mysql.yml
            service: clinic-mysql
    clinic-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: clinic-elasticsearch
